// Next.js
import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { muktaMahee } from '@/styles/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  themeColor: '#7478d2',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={muktaMahee.className}>{children}</body>
    </html>
  );
}
